version: '3'

services:

  mywww:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    # bunkerized-nginx runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - autoconf:/etc/nginx
    environment:
      - SERVER_NAME=                                              # must be left blank if you don't want to setup "static" conf
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_PROXY_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
    labels:
      - "bunkerized-nginx.AUTOCONF"
    networks:
      - myappnet

  myautoconf:
    image: bunkerity/bunkerized-nginx-autoconf
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - autoconf:/etc/nginx
    depends_on:
      - mywww

volumes:
  autoconf:

networks:
  myappnet:
    name: myappnet
