x-env: &env
  DATABASE_URI: "mariadb+pymysql://bunkerweb:changeme@bw-db:3306/db"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.0-beta
    container_name: bunkerweb
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # for QUIC
    environment:
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.0-beta
    container_name: bw-scheduler
    depends_on:
      - bunkerweb
    volumes:
      - bw-data:/data
    environment:
      <<: *env
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: ""
      MULTISITE: "yes"
      API_WHITELIST_IP: "127.0.0.0/24 10.20.30.0/24"
      SERVE_FILES: "no"
      USE_BUNKERNET: "no"
      USE_BLACKLIST: "no"
      USE_WHITELIST: "no"
      SEND_ANONYMOUS_REPORT: "no"
      USE_REAL_IP: "yes"
      REAL_IP_FROM: "10.0.0.0/8"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      COOKIE_FLAGS: ""
      COOKIE_AUTO_SECURE_FLAG: "no"
      KEEP_UPSTREAM_HEADERS: "*"
      UI_HOST: "http://bw-ui:7000"
      CUSTOM_CONF_HTTP_increase_server_names_hash_bucket_size: "server_names_hash_bucket_size 256;"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-ui:
    image: bunkerity/bunkerweb-ui:1.6.0-beta
    container_name: bw-ui
    ports:
      - "7000:7000"
    environment:
      <<: *env
      CHECK_PRIVATE_IP: "no"
      ALWAYS_REMEMBER: "yes"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-db

  bw-db:
    image: mariadb:11
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "bunkerweb"
      MYSQL_PASSWORD: "changeme" # replace with a stronger password
    volumes:
      - bw-db:/var/lib/mysql
    restart: "unless-stopped"
    networks:
      - bw-db

volumes:
  bw-data:
  bw-db:


networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  bw-db:
    name: bw-db
