site_name: BunkerWeb documentation
site_url: https://docs.bunkerweb.io/
repo_url: https://github.com/bunkerity/bunkerweb
site_description: Documentation of BunkerWeb, the open source and next generation WAF.
copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> Bunkerity
#remote_branch: ?
#remote_name: ?

nav:
  - Introduction: 'index.md'
  - Concepts: 'concepts.md'
  - Integrations: 'integrations.md'
  - Quickstart guide: 'quickstart-guide.md'
  - Features: 'features.md'
  - Advanced usages: 'advanced.md'
  # - Security tuning: 'security-tuning.md'
  - Web UI: 'web-ui.md'
  - Upgrading: 'upgrading.md'
  - Troubleshooting: 'troubleshooting.md'
  - Plugins: 'plugins.md'
  - Professional services: 'professional-services.md'
  - About: 'about.md'

theme:
  name: material
  locale: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.code.copy
  custom_dir: docs/overrides

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js
  - https://chatbot.bunkerweb.io/static/js/chatbot.js

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  version:
    provider: mike
    version: latest

  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fTf46FmtyD
    - icon: fontawesome/brands/github
      link: https://github.com/bunkerity
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/bunkerity/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bunkerity

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#0b5577"
        color: "white"
  - mike:
      canonical_version: latest
  - print-site
