version: '3'

services:

  mywww:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    # bunkerized-nginx runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./web-files:/www:ro
      - autoconf:/etc/nginx
    environment:
      - SERVER_NAME=admin.website.com                          # replace with your domain
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - admin.website.com_SERVE_FILES=no
      - admin.website.com_USE_AUTH_BASIC=yes
      - admin.website.com_AUTH_BASIC_USER=admin                # change it to something hard to guess
      - admin.website.com_AUTH_BASIC_PASSWORD=admin            # change it to something hard to guess
      - admin.website.com_USE_REVERSE_PROXY=yes
      - admin.website.com_REVERSE_PROXY_URL=/admin/            # change it to something hard to guess
      - admin.website.com_REVERSE_PROXY_HOST=http://myui:5000/  
      - admin.website.com_USE_MODSECURITY=no
    labels:
      - "bunkerized-nginx.UI"

  myui:
    image: bunkerity/bunkerized-nginx-ui
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - autoconf:/etc/nginx
    environment:
      - ABSOLUTE_URI=https://admin.website.com/admin/          # change it to your full URI

volumes:
  autoconf:
