x-env: &env
  API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
  # real IP settings
  USE_REAL_IP: "yes"
  REAL_IP_FROM: "10.10.10.0/24"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.6
    container_name: bunkerweb
    environment:
      <<: *env
    restart: "unless-stopped"
    networks:
      - net-proxy
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.6
    container_name: bw-scheduler
    depends_on:
      - bunkerweb
    volumes:
      - bw-storage:/data
    environment:
      <<: *env
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: "www.example.com" # replace with your domains
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      USE_REVERSE_PROXY: "yes"
      REVERSE_PROXY_URL: "/"
      REVERSE_PROXY_HOST: "http://myapp:8080"
    restart: "unless-stopped"
    networks:
      - bw-universe

  myproxy:
    image: haproxy:3.1-alpine
    depends_on:
      - bunkerweb
    ports:
      - "80:8080/tcp"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - net-proxy

  myapp:
    image: nginxdemos/nginx-hello
    networks:
      - bw-services

volumes:
  bw-storage:


networks:
  bw-universe:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  net-proxy:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
  bw-services:
