# clone the repository https://github.com/bigbluebutton/docker into the root directory and run the following command: ./scripts/setup
# when executing the file ./scripts/setup do this:

# Should greenlight be included? (y/n): y
# Should an automatic HTTPS Proxy be included? (y/n): n
# ...
# Please enter the domain name: www.example.com (your domain name)

# after generating your bigbluebutton docker-compose.yml file, you can modify the following to add bunkerweb to it

services:

  ...

  nginx:
    ...
    # comment this line
    # network_mode: host
    # then add the following lines
    networks:
      bbb-net:
        ipv4_address: 10.7.7.253
    ...

  ...

  bunkerweb:
    image: bunkerity/bunkerweb:1.6.6-rc3
    container_name: bunkerweb
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # for QUIC
    environment:
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
    restart: "unless-stopped"
    networks:
      bbb-net:
        ipv4_address: 10.7.7.254
      bw-universe:

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.6-rc3
    container_name: bw-scheduler
    depends_on:
      - bunkerweb
    volumes:
      - bw-storage:/data
    environment:
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: "${DOMAIN}"
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      AUTO_LETS_ENCRYPT: "yes"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      USE_REVERSE_PROXY: "yes"
      REVERSE_PROXY_WS: "yes"
      REVERSE_PROXY_URL: "/"
      REVERSE_PROXY_HOST: "http://10.7.7.253:8080"
    restart: "unless-stopped"
    networks:
      - bw-universe

  ...

volumes:
  ...
  bw-storage:

networks:
  ...
  bw-universe:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
