services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.6.5-rc4
    container_name: bunkerweb
    ports:
      - "80:8080/tcp"
      - "443:8443/tcp"
      - "443:8443/udp" # for QUIC
    environment:
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
    restart: "unless-stopped"
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.6.5-rc4
    container_name: bw-scheduler
    depends_on:
      - bunkerweb
    volumes:
      - bw-storage:/data
    environment:
      BUNKERWEB_INSTANCES: "bunkerweb"
      SERVER_NAME: "www.example.com" # replace with your domain
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      AUTO_LETS_ENCRYPT: "yes"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      MAX_CLIENT_SIZE: "50m"
      USE_REVERSE_PROXY: "yes"
      REVERSE_PROXY_URL: "/"
      REVERSE_PROXY_HOST: "http://myps"
      # Once the installation is done, you can remove these lines
      LIMIT_REQ_URL_1: "/install/index.php"
      LIMIT_REQ_RATE_1: "8r/s"
    restart: "unless-stopped"
    networks:
      - bw-universe

  myps:
    image: prestashop/prestashop:8
    volumes:
      - ps-data:/var/www/html
    environment:
      DB_SERVER: "mydb"
      DB_USER: "user"
      DB_PASSWD: "db-user-pwd" # replace with a stronger password (must match MYSQL_PASSWORD)
      DB_PREFIX: "prefix_" # replace with a random prefix (good security practice)
      DB_NAME: "prestashop"
      PS_ENABLE_SSL: "1"
      ADMIN_MAIL: "admin@example.com" # change to the prestashop admin email
      ADMIN_PASSWD: "changeme" # change to the prestashop admin password
      PS_FOLDER_ADMIN: "administration" # change to the prestashop admin folder
    networks:
      - prestashop-net
      - bw-services

  mydb:
    image: mariadb:11
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "db-root-pwd" # replace with a stronger password
      MYSQL_DATABASE: "prestashop"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "db-user-pwd" # replace with a stronger password (must match DB_PASSWD)
    networks:
      - prestashop-net

volumes:
  bw-storage:
  ps-data:
  db-data:


networks:
  bw-universe:
    name: bw-universe
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
    name: bw-services
  prestashop-net:
    name: prestashop-net
