name: Run Clang Static Analysis
on:
  push:
  pull_request:
  schedule:
    - cron: '3 20 * * SUN'
jobs:
  clang-analyzer:
    name: Clang static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install clang-tools libipc-run3-perl
      - run: ./bootstrap
      - run: scan-build ./configure
        env:
          CFLAGS: -std=c99 -Wall -Wextra -Werror -Wno-unused-function -Wno-unused-parameter -Wno-unknown-pragmas
      - run: cd src; scan-build --status-bugs make; cd ..
      - run: cd bin; scan-build --status-bugs make; cd ..
