version: '3'

services:

  myreverse:
    image: bunkerity/bunkerized-nginx
    restart: always
    depends_on:
      - myws
    ports:
      - 80:8080
      - 443:8443
    # bunkerized-nginx runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - SERVER_NAME=www.website.com                          # replace with your domain
      - SERVE_FILES=no
      - DISABLE_DEFAULT_SERVER=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - AUTO_LETS_ENCRYPT=yes
      - USE_PROXY_CACHE=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/ws/
      - REVERSE_PROXY_HOST=http://myws:8010/
      - REVERSE_PROXY_WS=yes

  myws:
    image: ksdn117/web-socket-test
    restart: always
