name: Generate documentation PDF (REUSABLE)

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout source code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Install Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.10"
      - name: Install doc dependencies
        run: pip install --no-cache-dir --require-hashes -r docs/requirements.txt && sudo apt install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Install chromium
        run: sudo apt install chromium-browser
      - name: Install node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 18
      - name: Install puppeteer
        run: cd docs && npm install
      - name: Run mkdocs serve in background
        run: mkdocs serve & sleep 10
      - name: Run pdf script
        run: node docs/misc/pdf.js http://localhost:8000/print_page/ BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf 'BunkerWeb documentation v${{ inputs.VERSION }}'
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf
          path: BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf
