name: Generate documentation PDF (REUSABLE)

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.10"
      - name: Install doc dependencies
        run: pip install --no-cache-dir --require-hashes -r docs/requirements.txt && sudo apt update && sudo apt install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Install chromium
        run: sudo apt update && sudo apt install chromium-browser
      - name: Install node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
      - name: Install puppeteer
        run: cd docs && npm install
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - name: Run mkdocs serve in background
        run: mkdocs serve & sleep 120
      - name: Run pdf script
        run: node docs/misc/pdf.js http://localhost:8000/print_page/ BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf 'BunkerWeb documentation v${{ inputs.VERSION }}'
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf
          path: BunkerWeb_documentation_v${{ inputs.VERSION }}.pdf
