name: Automatic test for Linux

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build Debian with systemd
        run: docker build -t debian-systemd -f tests/Dockerfile-debian .
      - name: Build Ubuntu with systemd
        run: docker build -t ubuntu-systemd -f tests/Dockerfile-ubuntu .
      - name: Build CentOS with systemd
        run: docker build -t centos-systemd -f tests/Dockerfile-centos .
      - name: Build Fedora with systemd
        run: docker build -t fedora-systemd -f tests/Dockerfile-fedora .
      - name: Debian test
        run: ./tests/linux-run.sh debian-systemd test-debian
      - name: Ubuntu test
        run: ./tests/linux-run.sh ubuntu-systemd test-ubuntu
      - name: CentOS test
        run: ./tests/linux-run.sh centos-systemd test-centos
      - name: Fedora test
        run: ./tests/linux-run.sh fedora-systemd test-fedora
