name: Push documentation (REUSABLE)

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string
      ALIAS:
        required: true
        type: string
      HIDDEN:
        required: false
        type: boolean
        default: false
    secrets:
      BUNKERBOT_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.BUNKERBOT_TOKEN }}
      - name: Replace VERSION
        if: inputs.VERSION == 'testing'
        run: chmod +x ./misc/update-version.sh && ./misc/update-version.sh testing
      - name: Setup git user
        run: |
          git config --global user.name "BunkerBot"
          git config --global user.email "bunkerbot@bunkerity.com"
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.10"
      - name: Install doc dependencies
        run: pip install --no-cache-dir --require-hashes -r docs/requirements.txt && sudo apt install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Set up hidden documentation
        if: inputs.HIDDEN == true
        run: |
          mike deploy --update-aliases --alias-type=copy ${{ inputs.VERSION }} ${{ inputs.ALIAS }}
          mike props ${{ inputs.VERSION }} --set hidden=true --push
      - name: Deploy documentation
        if: inputs.HIDDEN == false
        run: mike deploy --update-aliases --push --alias-type=copy ${{ inputs.VERSION }} ${{ inputs.ALIAS }}
      - name: Set default doc
        if: inputs.ALIAS == 'latest'
        run: mike set-default --push latest
